
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#    spring.datasource.url=jdbc:mysql://localhost:3306/springdubbo?characterEncoding=UTF-8&allowMultiQueries=true
#    spring.datasource.username=root
#    spring.datasource.password=1229971135
#    spring.datasource.driver-class-name=com.mysql.jdbc.Driver