#spring.thymeleaf.cache=false
#spring.thymeleaf.mode=LEGACYHTML5
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8763
spring:
  application:
    name: cloud-provider
  datasource:
    url: jdbc:mysql://localhost:3306/feng?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #    useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cen.cloudapi.entity