eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: cloud-zuul
zuul:
  routes:
    api-a:
      path: /user1/**
      serviceId: cloud-ribbon
    api-b:
      path: /user2/**
      serviceId: cloud-provider