package com.cen.cloudprovider.mapper;

import com.cen.cloudapi.entity.Article;
import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int updateByPrimaryKey(Article record);
}