package com.cen.cloudprovider.mapper;

import com.cen.cloudapi.entity.MenuRole;
import java.util.List;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    MenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    List<MenuRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    int updateByPrimaryKey(MenuRole record);
}