package com.cen.cloudapi.entity;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.articleid
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private String articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private String article;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.id
     *
     * @return the value of sys_article.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.id
     *
     * @param id the value for sys_article.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.articleid
     *
     * @return the value of sys_article.articleid
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public String getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.articleid
     *
     * @param articleid the value for sys_article.articleid
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setArticleid(String articleid) {
        this.articleid = articleid == null ? null : articleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.article
     *
     * @return the value of sys_article.article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.article
     *
     * @param article the value for sys_article.article
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setArticle(String article) {
        this.article = article == null ? null : article.trim();
    }
}