package com.cen.cloudapi.entity;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_remark
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private String deptRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.flag
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept
     *
     * @return the value of sys_dept.dept
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept
     *
     * @param dept the value for sys_dept.dept
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_remark
     *
     * @return the value of sys_dept.dept_remark
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public String getDeptRemark() {
        return deptRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_remark
     *
     * @param deptRemark the value for sys_dept.dept_remark
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setDeptRemark(String deptRemark) {
        this.deptRemark = deptRemark == null ? null : deptRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.flag
     *
     * @return the value of sys_dept.flag
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.flag
     *
     * @param flag the value for sys_dept.flag
     *
     * @mbg.generated Mon May 06 17:01:48 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}